### ISSUE TITLE
Cant Play with both PCs on Server

### ISSUE THREAD

**Issue by Dan0rk** [CraftyBoss/SuperMarioOdysseyOnline#41]
It works great if only one PC is on the Server but as soon i try to connect my other Pc, both will constantly loss connection and regain connection just after. So there looping in the Connecting Screen. But only if both Pcs are connected.
I now this mod is still in development but if there is any fix please tell me.

**Comment by Istador** [comment]
This isn't the support for the mod. That'd be in Discord.

If you see a `"Disconnecting already connected client"` message in the server log, it's because both users are using the same profile ID, kicking each other out.

Make sure that you followed all the steps in the guides for the [Ryujinx](https://smoo.it/#/play/ryujinx) or [yuzu](https://smoo.it/#/play/yuzu) emulator.

**Comment by speyejack** [comment]
As Istador already said, please check the [site](https://smoo.it) for troubleshooting. If you still need help troubleshooting, please ask nicely on the discord.
